#server:
#  port: 10086
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    region: region-east
#    service-url:
#      zone1: http://localhost:10086/eureka/
#      zone2: http://localhost:10010/eureka/
#    availability-zones:
#      region-east: zone1,zone2
#  instance:
#    metadataMap.Zone: zone1
